os:
  - Visual Studio 2022

environment:
  matrix:
    - ACTION: vs2022

platform:
  - x64
    
configuration:
  - Release

install:
  - bin\premake5.exe %ACTION%
  
build:
  project: build\$(ACTION)\xatlas.sln
